blueprint:
  name: Lights Flash
  description: >
    Repeatedly flash selected lights in chosen colors with configurable on/off delays,
    then restore their previous state once the script stops.
  domain: script
  source_url: https://raw.githubusercontent.com/Bluscream/hass-blueprints/main/lights_flash.yaml
  homeassistant:
    min_version: "2024.10.0"
  input:
    target_lights:
      name: Target lights
      description: The lights to flash.
      selector:
        entity:
          domain: light
          multiple: true
    primary_color:
      name: Primary color
      description: Color used during the first half of each flash cycle.
      selector:
        color_rgb: {}
    secondary_color:
      name: Secondary color
      description: Color used during the second half of each flash cycle. Leave black for an "off" phase.
      selector:
        color_rgb: {}
    primary_brightness_pct:
      name: Primary brightness (%)
      description: Brightness while the primary color is active.
      default: 100
      selector:
        number:
          min: 1
          max: 100
          step: 1
          unit_of_measurement: "%"
    secondary_brightness_pct:
      name: Secondary brightness (%)
      description: Brightness while the secondary color is active. Set to 0 to fully turn lights off during this phase.
      default: 0
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
    on_duration:
      name: On duration
      description: How long the lights stay on each cycle.
      default:
        seconds: 1
      selector:
        duration:
          enable_millisecond: true
    off_duration:
      name: Off duration
      description: How long the lights stay off each cycle.
      default:
        seconds: 1
      selector:
        duration:
          enable_millisecond: true
    on_transition_ms:
      name: On transition (ms)
      description: Transition time applied when turning lights on.
      default: 0
      selector:
        number:
          min: 0
          max: 5000
          step: 50
          unit_of_measurement: ms
    off_transition_ms:
      name: Off transition (ms)
      description: Transition time applied when turning lights off.
      default: 0
      selector:
        number:
          min: 0
          max: 5000
          step: 50
          unit_of_measurement: ms

variables:
  snapshot_scene_id: lights_backup
  primary_color: !input primary_color
  secondary_color: !input secondary_color
  primary_brightness_pct: !input primary_brightness_pct
  secondary_brightness_pct: !input secondary_brightness_pct
  on_duration: !input on_duration
  off_duration: !input off_duration
  on_transition_ms: !input on_transition_ms
  off_transition_ms: !input off_transition_ms
  on_transition: >-
    {{ (on_transition_ms | int) / 1000 }}
  off_transition: >-
    {{ (off_transition_ms | int) / 1000 }}
  script_entity: "{{ this.entity_id }}"
  primary_is_off: >-
    {{ ((primary_color[0] | default(0)) == 0 and (primary_color[1] | default(0)) == 0 and (primary_color[2] | default(0)) == 0)
       or (primary_brightness_pct | int) < 1 }}
  secondary_is_off: >-
    {{ ((secondary_color[0] | default(0)) == 0 and (secondary_color[1] | default(0)) == 0 and (secondary_color[2] | default(0)) == 0)
       or (secondary_brightness_pct | int) < 1 }}

sequence:
  - action: scene.create
    data:
      scene_id: "{{ snapshot_scene_id }}"
      snapshot_entities: !input target_lights
  - repeat:
      while:
        - condition: template
          value_template: "{{ is_state(script_entity, 'on') }}"
      sequence:
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ not primary_is_off }}"
              sequence:
                - action: light.turn_on
                  target:
                    entity_id: !input target_lights
                  data:
                    rgb_color: !input primary_color
                    brightness_pct: "{{ primary_brightness_pct }}"
                    transition: "{{ on_transition }}"
          default:
            - action: light.turn_off
              target:
                entity_id: !input target_lights
              data:
                transition: "{{ on_transition }}"
        - delay: !input on_duration
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ not secondary_is_off }}"
              sequence:
                - action: light.turn_on
                  target:
                    entity_id: !input target_lights
                  data:
                    rgb_color: !input secondary_color
                    brightness_pct: "{{ secondary_brightness_pct }}"
                    transition: "{{ off_transition }}"
          default:
            - action: light.turn_off
              target:
                entity_id: !input target_lights
              data:
                transition: "{{ off_transition }}"
        - delay: !input off_duration
  - action: scene.turn_on
    target:
      entity_id: "{{ 'scene.' ~ snapshot_scene_id }}"
  - action: scene.delete
    target:
      entity_id: "{{ 'scene.' ~ snapshot_scene_id }}"

mode: restart
max_exceeded: silent
icon: mdi:alarm-light
