blueprint:
  name: Lights Flash
  author: Bluscream
  source_url: https://raw.githubusercontent.com/Bluscream/hass-blueprints/main/lights_flash.yaml
  description: >
    Repeatedly flash selected lights in chosen colors with configurable on/off delays,
    then restore their previous state once the script stops.
  domain: script
  homeassistant:
    min_version: "2024.10.0"
  input:
    target_lights:
      name: Target lights
      description: The lights to flash.
      selector:
        entity:
          domain: light
          multiple: true
    snapshot_scene:
      name: Snapshot scene
      description: Scene entity used to store and restore the lights' state.
      default: scene.lights_backup
      selector:
        entity:
          domain: scene
    primary_section:
      name: Primary phase
      icon: mdi:flash
      input:
        primary_color:
          name: Color
          description: Color used during the first half of each flash cycle.
          selector:
            color_rgb: {}
        primary_brightness_pct:
          name: Brightness
          description: Brightness while the primary color is active.
          default: 100
          selector:
            number:
              min: 0
              max: 100
              step: 1
              unit_of_measurement: "%"
        primary_duration:
          name: Duration
          description: How long the lights stay in the primary color each cycle.
          default:
            seconds: 1
          selector:
            duration:
              enable_millisecond: true
        primary_transition_duration:
          name: Transition duration
          description: Transition time applied when activating the primary color.
          default:
            seconds: 0
          selector:
            duration:
              enable_millisecond: true
    secondary_section:
      name: Secondary phase
      icon: mdi:flash-outline
      input:
        secondary_color:
          name: Color
          description: Color used during the second half of each flash cycle. Leave black for an "off" phase.
          selector:
            color_rgb: {}
        secondary_brightness_pct:
          name: Brightness
          description: Brightness while the secondary color is active. Set to 0 to fully turn lights off during this phase.
          default: 0
          selector:
            number:
              min: 0
              max: 100
              step: 1
              unit_of_measurement: "%"
        secondary_duration:
          name: Duration
          description: How long the lights stay in the secondary color/off each cycle.
          default:
            seconds: 1
          selector:
            duration:
              enable_millisecond: true
        secondary_transition_duration:
          name: Transition duration
          description: Transition time applied when activating the secondary color/off phase.
          default:
            seconds: 0
          selector:
            duration:
              enable_millisecond: true

variables:
  snapshot_scene_entity: !input snapshot_scene
  primary_color: !input primary_color
  secondary_color: !input secondary_color
  primary_brightness_pct: !input primary_brightness_pct
  secondary_brightness_pct: !input secondary_brightness_pct
  primary_duration: !input primary_duration
  secondary_duration: !input secondary_duration
  primary_transition_duration: !input primary_transition_duration
  secondary_transition_duration: !input secondary_transition_duration
  primary_transition: >-
    {{ as_timedelta(primary_transition_duration).total_seconds() }}
  secondary_transition: >-
    {{ as_timedelta(secondary_transition_duration).total_seconds() }}
  script_entity: "{{ this.entity_id }}"
  primary_is_off: >-
    {{ ((primary_color[0] | default(0)) == 0 and (primary_color[1] | default(0)) == 0 and (primary_color[2] | default(0)) == 0)
       or (primary_brightness_pct | int) < 1 }}
  secondary_is_off: >-
    {{ ((secondary_color[0] | default(0)) == 0 and (secondary_color[1] | default(0)) == 0 and (secondary_color[2] | default(0)) == 0)
       or (secondary_brightness_pct | int) < 1 }}

sequence:
  - action: scene.create
    data:
      scene_id: "{{ snapshot_scene_entity.split('.')[-1] }}"
      snapshot_entities: !input target_lights
  - repeat:
      while:
        - condition: template
          value_template: "{{ is_state(script_entity, 'on') }}"
      sequence:
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ not primary_is_off }}"
              sequence:
                - action: light.turn_on
                  target:
                    entity_id: !input target_lights
                  data:
                    rgb_color: !input primary_color
                    brightness_pct: "{{ primary_brightness_pct }}"
                    transition: "{{ primary_transition }}"
          default:
            - action: light.turn_off
              target:
                entity_id: !input target_lights
              data:
                transition: "{{ primary_transition }}"
        - delay: !input primary_duration
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ not secondary_is_off }}"
              sequence:
                - action: light.turn_on
                  target:
                    entity_id: !input target_lights
                  data:
                    rgb_color: !input secondary_color
                    brightness_pct: "{{ secondary_brightness_pct }}"
                    transition: "{{ secondary_transition }}"
          default:
            - action: light.turn_off
              target:
                entity_id: !input target_lights
              data:
                transition: "{{ secondary_transition }}"
        - delay: !input secondary_duration
  - action: scene.turn_on
    target:
      entity_id: !input snapshot_scene
  - action: scene.delete
    target:
      entity_id: !input snapshot_scene

mode: restart
max_exceeded: silent
icon: mdi:alarm-light
