blueprint:
  name: Fade Light to Level
  author: Bluscream
  description: Fade one or more lights to a target brightness over a given transition.
  domain: script
  source_url: https://raw.githubusercontent.com/Bluscream/hass-blueprints/main/motion_illuminance_activated_entity.yaml
  homeassistant:
    min_version: "2024.6.0"
  input:
    target_lights:
      name: Target lights
      description: Lights, devices, or areas to fade.
      selector:
        target:
          entity:
            domain: light
    end_pct:
      name: Target brightness (%)
      description: Desired final brightness as a percentage.
      default: 50
      selector:
        number:
          min: 0
          max: 100
          step: 1
          mode: slider
          unit_of_measurement: "%"
    transition_seconds:
      name: Transition time (seconds)
      description: Time in seconds to reach the final brightness.
      default: 5
      selector:
        number:
          min: 0
          max: 600
          step: 1

mode: parallel
max_exceeded: silent

sequence:
  - service: light.turn_on
    target: !input target_lights
    data:
      brightness_pct: !input end_pct
      transition: !input transition_seconds
