# Moved from https://gist.github.com/Bluscream/38ea188282c17f9a1066a4f6d4ca5fe5/edit
blueprint:
    name: Multiclick
    description: Different Actions on Short, Long, Very Long, Double and triple click
    domain: automation
    input:
        switch_id:
            name: Binary sensor entity
            description: The binary_sensor used to trigger the automation
            selector:
                entity:
                    domain: binary_sensor
        short_click_action:
            name: Short click action
            description: The action(s) to launch for a single short click
            default: []
            selector: 
                action:
        double_click_action:
            name: Double click action
            description: The action(s) to launch for a double click
            default: []
            selector: 
                action:
        triple_click_action:
            name: Triple click action
            description: The action(s) to launch for a triple click
            default: []
            selector: 
                action:
        long_click_action:
            name: Long click action
            description: The action(s) to launch for a long click
            default: []
            selector: 
                action:
        long_click_delay:
            name: Long click delay
            description: The delay in seconds for a long click
            default: 0.5
            selector:
                number:
                 min: 0.0
                 max: 10.0
                 unit_of_measurement: seconds
        very_long_click_action:
            name: Very long click action
            description: The action(s) to launch for a very long click
            default: []
            selector: 
                action:
        very_long_click_delay:
            name: Very long click delay
            description: The delay in seconds for a very long click
            default: 1.0
            selector:
                number:
                 min: 0.0
                 max: 10.0
                 unit_of_measurement: seconds
trigger:
    - platform: state
        entity_id: !input switch_id
        to: 'on'
mode: single
action:
    - variables: # create variable cause we need those in templates
        switch_id: !input switch_id
        double_click_action: !input double_click_action
        triple_click_action: !input triple_click_action
    - wait_template: "{{ is_state(switch_id, 'off') }}"
        timeout: !input long_click_delay
        continue_on_timeout: true
    - choose:
      - conditions: "{{ not wait.completed }}" # long click
        sequence: !input long_click_action
  default:
    - choose:
        - conditions: "{{ double_click_action | length > 0 }}" # only wait for second click if a n action is defined for it to be more reactive
          sequence:
            - wait_template: "{{ is_state(switch_id, 'on') }}" # second click?
              timeout: !input long_click_delay
              continue_on_timeout: true
            - choose:
                - conditions: "{{ not wait.completed }}" # single click
                  sequence: !input short_click_action
                - conditions: "{{ triple_click_action | length > 0 }}" # waiting for third click
                  sequence:
                    - wait_template: "{{ is_state(switch_id, 'on') }}" # third click?
                      timeout: !input long_click_delay
                      continue_on_timeout: true
                    - choose:
                        - conditions: "{{ not wait.completed }}" # triple click
                          sequence: !input triple_click_action
                        - conditions: "{{ very_long_click_action | length > 0 }}" # waiting for fourth click
                          sequence:
                            - wait_template: "{{ is_state(switch_id, 'on') }}" # fourth click?
                              timeout: !input very_long_click_delay
                              continue_on_timeout: true
                            - conditions: "{{ not wait.completed }}" # very long click
                              sequence: !input very_long_click_action
              default: !input double_click_action # double click
      default: !input short_click_action
