blueprint:
  name: Multi Stage Light Blueprint
  author: Bluscream
  description: Adjusts light levels based on time of day while a trigger light remains on.
  domain: automation
  source_url: https://raw.githubusercontent.com/Bluscream/hass-blueprints/main/multi_stage_light.yaml
  homeassistant:
    min_version: "2024.6.0"

  input:
    trigger_light:
      name: Trigger Light
      description: Light entity whose state initiates the automation.
      selector:
        entity:
          domain: light

    target_lights:
      name: Target Lights
      description: Lights to control while the trigger is active.
      selector:
        target:
          entity:
            domain: light

    trigger_state_duration:
      name: Trigger State Duration
      description: Duration the trigger light must stay on before the automation starts.
      default:
        seconds: 1
      selector:
        duration: {}

    repeat_delay:
      name: Refresh Interval
      description: How often to re-assert the target light settings while the trigger stays on.
      default:
        minutes: 5
      selector:
        duration: {}

    day_brightness:
      name: Daytime Brightness (%)
      description: Brightness percentage to use during the day.
      default: 90
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    day_temperature:
      name: Daytime Color Temperature (mired)
      description: Color temperature to apply during the day.
      default: 350
      selector:
        number:
          min: 153
          max: 500

    night_brightness:
      name: Nighttime Brightness (%)
      description: Brightness percentage to use at night.
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    night_temperature:
      name: Nighttime Color Temperature (mired)
      description: Color temperature to apply at night.
      default: 450
      selector:
        number:
          min: 153
          max: 500

mode: restart
max_exceeded: silent

triggers:
  - trigger: state
    entity_id: !input trigger_light
    to: "on"
    for: !input trigger_state_duration

actions:
  - repeat:
      sequence:
        - choose:
            - conditions:
                - condition: template
                  value_template: >-
                    {{ 7 <= now().hour < 20 }}
              sequence:
                - action: light.turn_on
                  target: !input target_lights
                  data:
                    brightness_pct: !input day_brightness
                    color_temp: !input day_temperature
            - conditions:
                - condition: template
                  value_template: >-
                    {{ now().hour >= 20 or now().hour < 7 }}
              sequence:
                - action: light.turn_on
                  target: !input target_lights
                  data:
                    brightness_pct: !input night_brightness
                    color_temp: !input night_temperature
        - delay: !input repeat_delay
      until:
        - condition: state
          entity_id: !input trigger_light
          state: "off"
