# Moved from https://gist.github.com/Bluscream/38ea188282c17f9a1066a4f6d4ca5fe5/edit
blueprint:
  name: Multiclick
  description: Different actions for short, long, very long, double, and triple clicks.
  domain: automation
  source_url: https://raw.githubusercontent.com/Bluscream/hass-blueprints/main/multiclick.yaml
  homeassistant:
    min_version: "2024.6.0"
  input:
    switch_id:
      name: Trigger sensor
      description: Binary sensor used to detect the clicks.
      selector:
        entity:
          domain: binary_sensor
    short_click_action:
      name: Short click action
      description: Sequence to run for a single short click.
      default: []
      selector:
        action: {}
    double_click_action:
      name: Double click action
      description: Sequence to run for a double click.
      default: []
      selector:
        action: {}
    triple_click_action:
      name: Triple click action
      description: Sequence to run for a triple click.
      default: []
      selector:
        action: {}
    long_click_action:
      name: Long click action
      description: Sequence to run for a long click.
      default: []
      selector:
        action: {}
    long_click_delay:
      name: Long click delay (seconds)
      description: Duration the button must stay on to be considered a long click.
      default: 0.5
      selector:
        number:
          min: 0
          max: 10
          step: 0.1
          unit_of_measurement: seconds
    very_long_click_action:
      name: Very long click action
      description: Sequence to run for a very long click.
      default: []
      selector:
        action: {}
    very_long_click_delay:
      name: Very long click delay (seconds)
      description: Additional time after a long click to consider it a very long click.
      default: 1
      selector:
        number:
          min: 0
          max: 30
          step: 0.1
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

triggers:
  - trigger: state
    entity_id: !input switch_id
    to: "on"

actions:
  - variables:
      switch_id: !input switch_id
      short_click_action: !input short_click_action
      double_click_action: !input double_click_action
      triple_click_action: !input triple_click_action
      long_click_action: !input long_click_action
      very_long_click_action: !input very_long_click_action
      long_click_delay: !input long_click_delay
      very_long_click_delay: !input very_long_click_delay

  - wait_template: "{{ is_state(switch_id, 'off') }}"
    timeout: !input long_click_delay
    continue_on_timeout: true

  - choose:
      - conditions: "{{ not wait.completed }}"
        sequence: !input long_click_action
    default:
      - choose:
          - conditions: "{{ double_click_action | length > 0 }}"
            sequence:
              - wait_template: "{{ is_state(switch_id, 'on') }}"
                timeout: !input long_click_delay
                continue_on_timeout: true
              - choose:
                  - conditions: "{{ not wait.completed }}"
                    sequence: !input short_click_action
                  - conditions: "{{ triple_click_action | length > 0 }}"
                    sequence:
                      - wait_template: "{{ is_state(switch_id, 'on') }}"
                        timeout: !input long_click_delay
                        continue_on_timeout: true
                      - choose:
                          - conditions: "{{ not wait.completed }}"
                            sequence: !input triple_click_action
                          - conditions: "{{ very_long_click_action | length > 0 }}"
                            sequence:
                              - wait_template: "{{ is_state(switch_id, 'on') }}"
                                timeout: !input very_long_click_delay
                                continue_on_timeout: true
                              - conditions: "{{ not wait.completed }}"
                                sequence: !input very_long_click_action
                default: !input double_click_action
        default: !input short_click_action
