blueprint:
  name: Night Light (Time Based)
  author: Bluscream
  description: >
    Dim the lights when a trigger light turns on at night, otherwise brighten
    them. Converted from the original Hallway Night Light automation.
  domain: automation
  source_url: https://raw.githubusercontent.com/Bluscream/hass-blueprints/main/night_light_time.yaml
  homeassistant:
    min_version: "2024.6.0"
  input:
    trigger_light:
      name: Trigger light
      description: Light entity that starts this automation when it turns on.
      selector:
        entity:
          domain: light
    trigger_state_duration:
      name: Trigger state duration
      description: How long the trigger light must stay on before the automation runs.
      default:
        seconds: 1
      selector:
        duration: {}
    target_lights:
      name: Target lights
      description: The lights, devices, or areas to control.
      selector:
        target:
          entity:
            domain: light
    night_start:
      name: Night period start
      description: Time of day when the dimmed night lighting begins.
      default: "20:00:00"
      selector:
        time: {}
    night_end:
      name: Night period end
      description: Time of day when the night period ends.
      default: "07:00:00"
      selector:
        time: {}
    night_brightness:
      name: Night brightness
      description: Brightness percentage to use during the night period.
      default: 1
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider
    day_brightness:
      name: Day brightness
      description: Brightness percentage to use outside of the night period.
      default: 90
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider
    night_temperature:
      name: Night color temperature
      description: Mired color temperature to use during the night period.
      default: 500
      selector:
        number:
          min: 150
          max: 650
          unit_of_measurement: "mired"
    day_temperature:
      name: Day color temperature
      description: Mired color temperature to use outside of the night period.
      default: 500
      selector:
        number:
          min: 150
          max: 650
          unit_of_measurement: "mired"
    repeat_delay:
      name: Repeat delay
      description: Delay between repeat light commands.
      default:
        seconds: 10
      selector:
        duration: {}
    enable_time_triggers:
      name: Trigger when times are reached
      description: Toggle to switch lighting automatically at night/day boundaries.
      default: false
      selector:
        boolean: {}

mode: restart
max_exceeded: silent

variables:
  night_start: !input night_start
  night_end: !input night_end
  enable_time_triggers: !input enable_time_triggers

triggers:
  - trigger: state
    entity_id: !input trigger_light
    to: "on"
    for: !input trigger_state_duration
    id: trigger_light_on
  - trigger: time
    at: !input night_start
    id: night_start
    enabled: !input enable_time_triggers
  - trigger: time
    at: !input night_end
    id: night_end
    enabled: !input enable_time_triggers

actions:
  - repeat:
      count: 2
      sequence:
        - choose:
            - conditions:
                - condition: template
                  value_template: >-
                    {% set start = night_start %}
                    {% set end = night_end %}
                    {% set now_time = now().strftime('%H:%M:%S') %}
                    {% if start <= end %}
                      {{ start <= now_time < end }}
                    {% else %}
                      {{ now_time >= start or now_time < end }}
                    {% endif %}
              sequence:
                - action: light.turn_on
                  target: !input target_lights
                  data:
                    brightness_pct: !input night_brightness
                    color_temp: !input night_temperature
          default:
            - action: light.turn_on
              target: !input target_lights
              data:
                brightness_pct: !input day_brightness
                color_temp: !input day_temperature
        - delay: !input repeat_delay
